[package]
name = "ws-demo"
version = "0.1.0"
edition = "2021"

[dependencies]
futures-util = "0.3.31"
serde = {version="1.0.215", features = ["derive"]}
serde_json = "1.0.132"
tokio = {version="1.41.1",features=["full"]}
tokio-stream = "0.1.16"
warp = "0.3.7"
